app:
  version: 1.0.1
  name: BookManagement
  description: This is my application

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: BookManagement
  datasource:
    url: jdbc:h2:~/onedayboot
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.H2Dialect
        format_sql: true
#        show_sql: true
        hbm2ddl:
          auto: update

logging:
  level:
    # logger에서 SQL을 보기 위해 -> show_sql은 system.out으로 뜨기 때문에 주석으로 빼줘야 된다.
    org.hibernate.sql : debug