app:
  version: 1.0.1
  name: BookManagement
  description: This is my application

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
  datasource:
  h2:
    console:

  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update